---
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-docker-registry-config
  namespace: registry
  labels:
    app: docker-registry
    chart: docker-registry-1.9.1
    heritage: Tiller
    release: release-name
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: true
    version: 0.1
