---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: metallb
    chart: bitnami/metallb
    namespace: metallb-system
    version: 0.1.28
    wait: true
    values:
      - values.yaml
