---
controller:
  image:
    registry: docker.io
    repository: metallb/controller
    tag: v0.9.4

speaker:
  image:
    registry: docker.io
    repository: metallb/speaker
    tag: v0.9.4

configInline:
  peers:
  - peer-address: 192.168.1.1
    peer-asn: 64512
    my-asn: 64513
  address-pools:
  - name: default
    protocol: bgp
    addresses:
    - 192.168.2.0/24
