---

- name: Create a new primary partition
  parted:
    device: /dev/sda
    number: 1
    state: present

- name: Create a ext4 filesystem on /dev/sda1
  filesystem:
    fstype: ext4
    dev: /dev/sda1
    force: yes

- name: Get UUID for partition
  command: blkid -s UUID -o value /dev/sda1
  register: disk_blkid
  check_mode: no
  changed_when: false

- name: Mount /dev/sda1 to /mnt
  mount:
    path: /mnt
    src: "UUID={{ disk_blkid.stdout }}"
    fstype: ext4
    opts: defaults,noatime
    state: mounted

- name: Create a symbolic to directories
  file:
    src: "/mnt/{{ item | basename }}"
    dest: "{{ item }}"
    state: link
  loop: "{{ prepare_aditional_disk_directories }}"
