---

- name: Configure vim as default editor
  copy:
    content: "export EDITOR=vi"
    dest: /etc/profile.d/editor.sh

- name: Allow sudo without password
  lineinfile:
    path: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL"

- name: Set authorized keys
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ prepare_public_keys }}"

- name: Generate new machine-id
  shell: rm /etc/machine-id && systemd-machine-id-setup && touch /etc/machine-id-new
  args:
    creates: /etc/machine-id-new
  register: first_execution

- name: First execution
  when: first_execution.changed
  block:
  - name: Change user password
    user:
      name: "{{ ansible_user }}"
      password: "{{ prepare_password }}"
      update_password: always

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      force_apt_get: true
      update_cache: true

- name: Disable unused services
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop: "{{ prepare_unused_services }}"

- name: Install nfs client
  apt:
    name: "nfs-common"
    state: latest
    force_apt_get: true
    update_cache: true

- name: Remove unused cron
  file:
    state: absent
    path: /etc/cron.d/make_nas_processes_faster
