---

- name: Configure vim as default editor
  copy:
    content: "export EDITOR=vi"
    dest: /etc/profile.d/editor.sh

- name: Allow sudo without password
  lineinfile:
    path: /etc/sudoers
    regexp: "^%sudo"
    line: "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL"

- name: Generate new machine-id
  shell: rm /etc/machine-id && systemd-machine-id-setup && touch /etc/machine-id-new
  args:
    creates: /etc/machine-id-new
