---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-bot
  namespace: mlbroking
  labels:
    app: alerts-bot
spec:
  selector:
    matchLabels:
      app: alerts-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: alerts-bot
    spec:
      containers:
      - image: pando85/alerts-bot:arm64v8-latest
        name: alerts-bot
        imagePullPolicy: Always
        env:
          - name: ALERTS_BOT_STORAGE_FILE_PATH
            value: "/storage/alerts_bot.json"
          - name: ALERTS_BOT_LOG_LEVEL
            value: "INFO"
          - name: ALERTS_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: alerts-bot
                key: token
          - name: ALPHAVANTAGE_API_KEY
            valueFrom:
              secretKeyRef:
                name: alpha-vantage
                key: api_key
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.1
            memory: 10Mi
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /bin/ps -e | grep python
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
        - name: alerts-bot-persistent-storage
          mountPath: /storage
      volumes:
      - name: alerts-bot-persistent-storage
        persistentVolumeClaim:
          claimName: alerts-bot-claim
