---
apiVersion: v1
kind: Service
metadata:
  name: dataproxy-backend
  namespace: mlbroking
  labels:
    app: dataproxy
    tier: backend
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  ports:
  - name: dataproxy
    port: 8080
    targetPort: http
  selector:
    app: dataproxy
    tier: backend
