---

- hosts:
  - ceph
  #k8s nodes still can have monitors runnig if not node affinity defined
  - k8s-cluster
  become: true
  gather_facts: true
  vars_prompt:
    name: "nuke_confirmation"
    prompt: "This will DESTROY rook-ceph disks. Do you wish to continue? [Y/n]"
    default: "n"
    private: no
  any_errors_fatal: yes
  vars:
    rook_devices_query: "[?name==`{{ inventory_hostname }}`].devices[].name"
    rook_devices: "{{ ceph_nodes | json_query(rook_devices_query) }}"
  pre_tasks:
  - name: check confirmation
    fail:
      msg: "Abort."
    when: nuke_confirmation != "Y"
  tasks:
  - name: rook-ceph | remove /var/lib/rook
    become: true
    file:
      state: absent
      path: "/var/lib/rook"

  - name: rook-ceph | zap the drives
    become: true
    shell: >
      sgdisk --zap-all {{ item }} || true
    loop: "{{ rook_devices }}"

  - name: rook-ceph | remove lvm partitions
    become: true
    shell: "{{ item }}"
    loop:
    - ls /dev/mapper/ceph--* | xargs -I% -- fuser --kill %
    - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup clear %
    - ls /dev/mapper/ceph--* | xargs -I% -- dmsetup remove -f %
    - ls /dev/mapper/ceph--* | xargs -I% -- rm -rf %
    ignore_errors: true

  - name: rook-ceph | wipe the block device
    become: true
    command: "wipefs -af {{ item }}"
    loop: "{{ rook_devices }}"
