---

- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - geerlingguy.ntp

- import_playbook:  ../../playbooks/install/kubespray.yml

- import_playbook: ../../kubespray/cluster.yml

- import_playbook:  ../../playbooks/install/storage.yml
