---
- hosts: kube-master
  any_errors_fatal: true
  become: true
  tasks:
    - name: Install k8s module dependencies
      apt:
        name:
          - python3-yaml
          - python3-pip

    - name: Install openshift package
      pip:
        name: openshift>=0.6

  roles:
    - geerlingguy.helm
