---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: etcd-backup-claim
  namespace: backup-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "grigri-dataset-backup"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: backup-system
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: arm64
          containers:
          - name: backup-etcd
            image: quay.io/coreos/etcd:v3.3.12-arm64
            env:
            - name: ETCDCTL_API
              value: "3"
            command: ["/bin/sh"]
            args: ["-c", "etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/ssl/etcd/ssl/ca.pem --cert=/etc/ssl/etcd/ssl/node-k8s-odroid-2.pem --key=/etc/ssl/etcd/ssl/node-k8s-odroid-2.pem snapshot save /backup/etcd-snapshot.db"]
            volumeMounts:
            - mountPath: /etc/ssl/etcd/ssl/
              name: etcd-certs
              readOnly: true
            - mountPath: /backup
              name: backup
          restartPolicy: OnFailure
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
          tolerations:
          - effect: NoSchedule
            operator: Exists
          hostNetwork: true
          volumes:
          - name: etcd-certs
            hostPath:
              path: /etc/ssl/etcd/ssl/
              type: Directory
          - name: backup
            persistentVolumeClaim:
              claimName: etcd-backup-claim
