apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: smartmon
  namespace: monitoring
spec:
  groups:
  - name: smartmon
    rules:
    - alert: diskDisconnected
      annotations:
        message: 'disk "{{ $labels.disk }}" in instance {{ $labels.instance }} not active'
      expr: |
        smartmon_device_active < 1
      for: 10m
      labels:
        severity: critical
    - alert: diskHighTemperature
      annotations:
        message: 'disk "{{ $labels.disk }}" in instance {{ $labels.instance }}: temperature {{ $value }}'
      expr: |
        smartmon_temperature_celsius_raw_value > 41
      for: 5m
      labels:
        severity: warning
    - alert: diskHighTemperature
      annotations:
        message: 'disk "{{ $labels.disk }}" in instance {{ $labels.instance }}: temperature {{ $value }}'
      expr: |
        smartmon_temperature_celsius_raw_value > 51
      for: 5m
      labels:
        severity: critical
    - alert: diskReadErrorRate
      annotations:
        message: 'disk "{{ $labels.disk }}" in instance {{ $labels.instance }} is going to fail'
      expr: |
        smartmon_raw_read_error_rate_worst <= smartmon_raw_read_error_rate_threshold
      for: 5m
      labels:
        severity: critical
