apiVersion: v1
kind: ConfigMap
metadata:
  name: dataproxy-intraday
  namespace: mlbroking
data:
  intraday.py: |-
    #!/usr/bin/env python3
    import requests

    from datetime import datetime, timedelta


    CUSTOM_STOCKS = ['GOOGL', 'AMZN', 'AMD', 'MU', 'FB', 'INTC', 'NVDA', 'NXPI', 'QCOM', 'TSLA', 'TXN']
    ALL_NASDAQ = ['AAPL', 'MSFT', 'AMZN', 'FB', 'GOOG', 'GOOGL', 'INTC', 'CMCSA', 'CSCO', 'PEP', 'ADBE', 'AMGN', 'COST', 'NFLX', 'PYPL', 'NVDA', 'AVGO', 'TXN', 'CHTR', 'QCOM', 'SBUX', 'BKNG', 'GILD', 'CELG', 'MDLZ', 'FISV', 'ADP', 'TMUS', 'INTU', 'ISRG', 'CSX', 'TSLA', 'BIIB', 'MU', 'WBA', 'VRTX', 'AMAT', 'ILMN', 'ATVI', 'MAR', 'ROST', 'ADI', 'LRCX', 'KHC', 'NXPI', 'AMD', 'CTSH', 'REGN', 'ORLY', 'ADSK', 'XEL', 'MNST', 'SIRI', 'PAYX', 'EBAY', 'BIDU', 'JD', 'EA', 'CTAS', 'KLAC', 'WDAY', 'PCAR', 'DLTR', 'LULU', 'ALXN', 'WLTW', 'MELI', 'IDXX', 'VRSK', 'UAL', 'XLNX', 'MCHP', 'VRSN', 'CERN', 'FAST', 'NTES', 'ALGN', 'SNPS', 'ASML', 'EXPE', 'CDNS', 'INCY', 'CHKP', 'SWKS', 'CTRP', 'MXIM', 'WDC', 'SYMC', 'CTXS', 'ULTA', 'AAL', 'NTAP', 'WYNN', 'TTWO', 'BMRN', 'JBHT', 'LBTYK', 'HAS', 'FOXA', 'MYL', 'HSIC', 'FOX', 'LBTYA']
    STOCKS = ALL_NASDAQ


    def get_intraday_data(company_stock_name: str, date: datetime):
        response = requests.get(
            f'https://dataproxy.k8s.grigri/v1/stock/{company_stock_name}/{date.strftime("%Y-%m-%d")}')
        data_json = response.json()
        print(f'date: {date}    status_code: {response.status_code} len_data: {len(data_json)}')
        return data_json


    if __name__ == '__main__':
        day = datetime.today() - timedelta(days=2)
        for stock in STOCKS:
            print(f'Stock: {stock}')
            get_intraday_data(stock, day)
