# Create an empty PVC to demonstrate the restore process
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-demo-restore
  namespace: default
  labels:
    app: stash-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: stash-demo
  name: stash-demo
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      containers:
      - command:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
        - mountPath: /source/restored-data # This will be empty at first
          name: restored-volume
      restartPolicy: Always
      volumes:
      - name: source-data
        gitRepo:
          repository: https://github.com/appscode/stash-data.git
      - name: restored-volume
        persistentVolumeClaim:
          claimName: stash-demo-restore
