apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6CiAgLSBqb2IKICBncm91cF9pbnRlcnZhbDogNW0KICBncm91cF93YWl0OiAzMHMKICByZWNlaXZlcjogdGVsZWdyYW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJvdXRlczoKICAtIG1hdGNoOgogICAgICBhbGVydG5hbWU6IFdhdGNoZG9nCiAgICByZWNlaXZlcjogbnVsbApyZWNlaXZlcnM6CiAgLSBuYW1lOiB0ZWxlZ3JhbQogICAgd2ViaG9va19jb25maWdzOgogICAgLSBzZW5kX3Jlc29sdmVkOiBUcnVlCiAgICAgIHVybDogaHR0cDovL2FsZXJ0bWFuYWdlci10ZWxlZ3JhbS1mb3J3YXJkZXI6ODA4MC92MS9hbGVydHMvNzA1NTg4MQo=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
