---
- name: Prepare
  hosts: all
  tasks:
    - name: Install python-yaml
      apt:
        name: python-yaml
        state: present

    - name: Create neccesary directories
      file:
        state: directory
        path: "{{ item }}"
      loop:
        - /var/backups
        - /etc/kubernetes/manifests

    - name: Mock kube-apiserver config
      copy:
        dest: /etc/kubernetes/manifests/kube-apiserver.yaml
        content: |
          apiVersion: v1
          kind: Pod
          metadata:
            creationTimestamp: null
            labels:
              component: kube-apiserver
              tier: control-plane
            name: kube-apiserver
            namespace: kube-system
          spec:
            containers:
            - command:
              - kube-apiserver
              image: gcr.io/google-containers/kube-apiserver:v1.15.2
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 8
                httpGet:
                  host: 192.168.1.21
                  path: /healthz
                  port: 6443
                  scheme: HTTPS
                initialDelaySeconds: 15
                timeoutSeconds: 15
              name: kube-apiserver
              resources:
                requests:
                  cpu: 250m
              volumeMounts:
            hostNetwork: true
            priorityClassName: system-cluster-critical
            volumes:
          status: {}

