---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager-telegram-forwarder
  namespace: monitoring
spec:
  replicas: 2
  template:
    metadata:
      name: alertmanager-telegram-forwarder
      labels:
        app: alertmanager-telegram-forwarder
    spec:
      containers:
      - name: alertmanager-telegram-forwarder
        image: pando85/alertmanager-telegram-forwarder:0.2.0
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-bot
                key: token
        resources:
          limits:
            cpu: 200m
            memory: 128M
          requests:
            cpu: 100m
            memory: 40M
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
