---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager-telegram-forwarder
  namespace: monitoring
spec:
  replicas: 2
  template:
    metadata:
      name: alertmanager-telegram-forwarder
      labels:
        app: alertmanager-telegram-forwarder
      annotations:
        checksum/config: 5a96df1b5fd34fc91c95cc28bab921236bfff7ea6c94e46b3b3a4af6f175d0ba
    spec:
      containers:
      - name: alertmanager-telegram-forwarder
        image: pando85/alertmanager-telegram-forwarder:0.3.0
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-bot
                key: token
          - name: TEMPLATE_PATH
            value: "/etc/forwarder/message.j2"
        resources:
          limits:
            memory: 128M
          requests:
            cpu: 100m
            memory: 40M
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/forwarder
          name: alertmanager-forwarder-template
      volumes:
      - name: alertmanager-forwarder-template
        configMap:
          name: alertmanager-forwarder-template
