---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: alertmanager-telegram-forwarder
  name: alertmanager-telegram-forwarder
  namespace: monitoring
spec:
  ports:
  - name: alertmanager-telegram-forwarder
    port: 8080
    targetPort: http
  selector:
    app: alertmanager-telegram-forwarder
  type: ClusterIP

