---

apiVersion: v1
kind: Namespace
metadata:
  name: stock-market

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alerts-bot-claim
  namespace: stock-market
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alerts-bot
  namespace: stock-market
  labels:
    app: alerts-bot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alerts-bot
    spec:
      containers:
      - image: pando85/alerts-bot:arm64v8-latest
        name: alerts-bot
        imagePullPolicy: Always
        env:
          - name: ALERTS_BOT_STORAGE_FILE_PATH
            value: "/storage/alerts_bot.json"
          - name: ALERTS_BOT_LOG_LEVEL
            value: "INFO"
          - name: ALERTS_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: alerts-bot
                key: token
          - name: ALPHAVANTAGE_API_KEY
            valueFrom:
              secretKeyRef:
                name: alerts-bot
                key: alpha-vantage-api-key
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.1
            memory: 10Mi
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /bin/ps -e | grep python
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
        - name: alerts-bot-persistent-storage
          mountPath: /storage
      volumes:
      - name: alerts-bot-persistent-storage
        persistentVolumeClaim:
          claimName: alerts-bot-claim
