apiVersion: v1
kind: Service
metadata:
  name: arm-exporter
  namespace: monitoring
  labels:
    k8s-app: arm-exporter
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9243
      targetPort: http
  selector:
    app: arm-exporter
