apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: backup
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: carlosedp/minio:latest
        imagePullPolicy: Always
        args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: storage
          mountPath: "/storage"
      volumes:
      - name: storage
        nfs:
          server: node2
          path: "/mnt/mediahdd/Backups/"
---
apiVersion: v1
kind: Service
metadata:
  namespace: backup
  name: minio
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: backup
  annotations:
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - host: minio.internal.carlosedp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: minio
          servicePort: 9000
