---

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: nginx-ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: nginx-ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: udp-services
  namespace: nginx-ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
