---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    app: mlflow
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
