---

apiVersion: v1
kind: Namespace
metadata:
  name: test-webservices

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-nginx
  namespace: test-webservices
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1
        name: nginx
        imagePullPolicy: IfNotPresent
        # env:
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test-webservices
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: nginx

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: test-webservices
spec:
  rules:
  - host: nginx.internal.kubernetes
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
