---

apiVersion: v1
kind: Namespace
metadata:
  name: test-webservices

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openra
  namespace: test-webservices
  labels:
    app: openra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openra
  template:
    metadata:
      labels:
        app: openra
    spec:
      containers:
      - name: openra-server
        image: rmoriz/openra
        ports:
        - containerPort: 1234
          name: http
          protocol: TCP
        env:
        - name: Name
          value: "k8s Server"
        - name: Mod
          value: "ra"
        - name: ListenPort
          value: "1234"
        - name: ExternalPort
          value: "443"
        livenessProbe:
          httpGet:
            path: /
            port: 1234
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: openra
  namespace: test-webservices
  labels:
    app: openra
spec:
  type: NodePort
  ports:
    - port: 1234
      targetPort: 1234
  selector:
    app: openra

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openra
  namespace: test-webservices
spec:
  rules:
  - host: openra.internal.kubernetes
    http:
      paths:
      - path: /
        backend:
          serviceName: openra
          servicePort: 1234
