{
 "title": "Smartmon Textfile",
 "description": "Smartmon Texfile node_exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(smartmon_smartctl_version, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Unhealthy Disks",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "smartmon_device_smart_healthy{instance=~\"$instance\"} < 1"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "raw {{instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Raw Error Read Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_raw_read_error_rate_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "val {{instance}} {{disk}}"
    },
    {
     "expr": "avg(smartmon_spin_retry_count_raw_value{instance=~\"$instance\"}) by (instance, disk)",
     "legendFormat": "raw {{instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Current Pending Sectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_current_pending_sector_raw_value{instance=~\"$instance\"}",
     "legendFormat": "raw {{instance}} {{disk}}"
    },
    {
     "expr": "smartmon_current_pending_sector_value{instance=~\"$instance\"}",
     "legendFormat": "val {{instance}} {{disk}}"
    }
   ]
  },
  {
   "title": "Reallocated Sectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartmon_reallocated_sector_ct_raw_value{instance=~\"$instance\"}",
     "legendFormat": "raw {{instance}} {{disk}}"
    },
    {
     "expr": "smartmon_reallocated_sector_ct_value{instance=~\"$instance\"}",
     "legendFormat": "val {{instance}} {{disk}}"
    }
   ]
  }
 ]
}