apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-internal
  namespace: nginx-ingress
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
    app: nginx-ingress-internal
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.2.1
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/part-of: nginx-ingress
    app: nginx-ingress-internal


