repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: stable
  url:  https://charts.helm.sh/stable

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    chart: ingress-nginx/ingress-nginx
    version: 3.7.1
    values:
      - ./values.yaml
