---

- name: update-ca-certificates
  command: update-ca-certificates

- name: restart sshd
  command: systemctl restart sshd

- name: restart server
  reboot:

- name: update grub
  command: update-grub
