---

- hosts: all
  become: true
  tasks:
    - name: Prune everything
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes

