---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-s3
  namespace: registry-s3
  labels:
    app: docker-registry
    release: s3
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      level: info
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
