---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-s3
  namespace: registry-s3
  labels:
    app: docker-registry
    release: s3
spec:
  type: ClusterIP
  ports:
    - port: 5000
      protocol: TCP
      name: registry
      targetPort: 5000
  selector:
    app: docker-registry
    release: s3
