---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    k8s-app: etcd-server
  name: etcd
  namespace: kube-system
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 2379
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: etcd
    k8s-app: etcd-server
  name: etcd
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.1.11
  - ip: 192.168.1.22
  - ip: 192.168.1.31
  ports:
  - name: http-metrics
    port: 2379
    protocol: TCP
