---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pypiserver
  namespace: pypiserver
  labels:
    app: pypiserver
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
