---
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: netdata
  name: netdata
  namespace: netdata
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-netdata
  labels:
    app: netdata
rules:
- apiGroups:
  - ''
  resources:
  - services
  - events
  - endpoints
  - pods
  - nodes
  - componentstatuses
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - resourcequotas
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /version
  - /healthz
  - /metrics
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - nodes/metrics
  - nodes/spec
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-netdata
  labels:
    app: netdata
    chart: netdata-1.1.3
    release: release-name
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-netdata
subjects:
- kind: ServiceAccount
  name: netdata
  namespace: netdata
