---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-slave
  namespace: netdata
  labels:
    app: netdata
data:
  coredns:     |
      update_every: 1
      autodetection_retry: 0
      jobs:
        - url: http://127.0.0.1:9153/metrics

  kubelet:     |
      update_every: 1
      autodetection_retry: 0
      jobs:
        - url: http://127.0.0.1:10255/metrics

  kubeproxy:     |
      update_every: 1
      autodetection_retry: 0
      jobs:
        - url: http://127.0.0.1:10249/metrics

  netdata:     |
      [global]
        memory mode = none
      [health]
        enabled = no

  stream:     |
      [stream]
        enabled = yes
        destination = netdata:19999
        api key = 6e5a5564-8ff0-4bc5-8943-33f52803d2ee
        timeout seconds = 60
        buffer size bytes = 1048576
        reconnect delay seconds = 5
        initial clock resync iterations = 60


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-master
  namespace: netdata
  labels:
    app: netdata
data:
  health:     |
      SEND_TELEGRAM="YES"
      TELEGRAM_BOT_TOKEN="614277043:AAFMv2nVIJL3zUBWFreiIs1TWjBkJ6NvI3o"
      DEFAULT_RECIPIENT_TELEGRAM="7055881"

  netdata:     |
      [global]
        memory mode = save
        bind to = 0.0.0.0:19999
      [plugins]
        cgroups = no
        tc = no
        enable running new plugins = no
        check for new plugins every = 72000
        python.d = no
        charts.d = no
        go.d = no
        node.d = no
        apps = no
        proc = no
        idlejitter = no
        diskspace = no

  stream:     |
      [6e5a5564-8ff0-4bc5-8943-33f52803d2ee]
        enabled = yes
        history = 86400
        default memory mode = save
        health enabled by default = auto
        allow from = *
