---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
  namespace: monitoring
spec:
  ports:
  - name: blackbox-exporter
    port: 9115
    targetPort: http
  selector:
    app: blackbox-exporter
  type: ClusterIP

